Increase healthcheck timeout
Testing backups can take some time

diff --git a/root/etc/s6-overlay/s6-rc.d/init-mmonit-upgrade/run b/root/etc/s6-overlay/s6-rc.d/init-mmonit-upgrade/run
--- a/root/etc/s6-overlay/s6-rc.d/init-mmonit-upgrade/run
+++ b/root/etc/s6-overlay/s6-rc.d/init-mmonit-upgrade/run
@@ -72,6 +72,7 @@ if [ -e /config/version ]; then
 	    echo ${MMONIT_VERSION} > /config/version
 	    echo ${variant} > /config/.variant
 	else
+	    echo "Upgrade from ${old_version}-${old_variant} to ${MMONIT_VERSION} failed with $?"
 	    test -n "${restore}" && mv "/config/mmonit-${old_version}-${old_variant}" "/config/mmonit-${old_version}"
 	    test -n "${last_backup}" && /usr/local/sbin/mmonit_restore "${last_backup}"
 	    upgrade_failed "Upgrade script failed, see /config/${MMONIT_VERSION}/logs/upgrade-${old_version}-${MMONIT_VERSION}.log"
