Generalize and add support for backing up mysql

diff --git a/root/etc/periodic/hourly/mmonit_backup b/root/etc/periodic/hourly/mmonit_backup
--- a/root/etc/periodic/hourly/mmonit_backup
+++ b/root/etc/periodic/hourly/mmonit_backup
@@ -1,4 +1,4 @@
-#!/usr/bin/with-contenv sh
+#!/usr/bin/with-contenv bash
 
 log () {
     echo "$(date +'%F %T') ${*}" | tee -a /config/logs/backup.log
@@ -8,6 +8,16 @@ fail () {
     log "${*}"
     exit 1
 }
+
+backup_fail () {
+    test -n "${backup_filename}" && rm -f ${backup_filename}
+    test -n "${tmpfile}" && rm -f ${tmpfile}
+    log "${*}"
+    exit 1
+}
+
+# If we stay in /root we'll get warnings when find finishes
+cd /config/mmonit-${MMONIT_VERSION} || fail "Unable to cd into /config/mmonit-${MMONIT_VERSION}"
 
 test -d /backup || fail "/backup is not a directory"
 test -w /backup || fail "/backup is not writable directory"
@@ -32,51 +42,93 @@ case ${0} in
 	;;
     *)
 	fail "Unable to determine backup time from filename: ${0}"
-	''
+	;;
 esac
 
+# Parse the database URL
+if [[ ${MMONIT_DATABASE_URL} =~ ^([^:]+)://([^:]+):([^@]+)@([^:]+):([0-9]+)/([a-zA-Z0-9]+)$ ]]; then
+    database="${BASH_REMATCH[1]}"
+    database_user="${BASH_REMATCH[2]}"
+    database_password="${BASH_REMATCH[3]}"
+    database_host="${BASH_REMATCH[4]}"
+    database_port="${BASH_REMATCH[5]}"
+    database_name="${BASH_REMATCH[6]}"
+    suffix=sql
+    case "${database}" in
+	"mysql")
+	    backup_prog=mariadb-dump
+	    database_pkg=mariadb-client
+	    ;;
+	*)
+	    fail "Unsupported database type: ${database}"
+	    ;;
+    esac
+else
+    database=sqlite3
+    suffix=sq3
+    backup_prog=sqlite3
+    database_pkg=sqlite
+fi
+
+# Install the package we need
+which "${backup_prog}" >/dev/null || {
+    output=$(apk add -Uq "${database_pkg}" 2>&1)
+    test $? -ne 0 && fail "Unable to install ${database_pkg}: ${output}"
+}
+
 # Create backup filename and check that it exists
-backup_filename="mmonit_backup_$(date +'%FT%T')_${type}.sq3"
+backup_filename="mmonit_backup_$(date +'%FT%T')_${type}.${suffix}"
 test -e /backup/${backup_filename} && fail "/backup/${backup_filename} exists"
-tmpfile=$(mktemp -t ${progrname}.XXXXXXXXXX)
+tmpfile=$(mktemp -t ${progname}.XXXXXXXXXX)
 trap "rm -f ${backup_filename} ${tmpfile}" 1 2 3 13 15
 
 # Process backup per DB method
-case "${MMONIT_DATABASE_URL}" in
-    "mysql://")
-	fail "Backing up MySQL is not yet supported"
-	;;
-    "postgresql://")
-	fail "Backing up PostgresQL is not yet supported"
-	;;
-    ""|"sqlite://")  # Assume sqlist
-	which sqlite3 >/dev/null || {
-	    output=$(apk add -Uq sqlite 2>&1)
-	    test $? -ne 0 && fail "Unable to install sqlite3: ${output}"
-	}
+case "${database}" in
+    "mysql")
 	for try in $(seq 1 10); do
-	    output=$(s6-setuidgid abc sqlite3 /config/mmonit-${MMONIT_VERSION}/db/mmonit.db ".backup /backup/${backup_filename}" 2>&1)
+	    output=$(s6-setuidgid abc ${backup_prog} --no-defaults -h "${database_host}" -u "${database_user}" --password="${database_password}" --all-databases -r "/backup/${backup_filename}" 2>&1)
 	    test $? -eq 0 && break
 	    log "Backup failed (attempt ${try}): ${output}"
 	    sleep ${try}
 	done
 	;;
-    *)
-	fail "Unsupported database type: ${MMONIT_DATABASE_URL}"
+    "postgresql://")
+	fail "Backing up PostgresQL is not yet supported"
+	;;
+    ""|"sqlite://")  # Assume sqlist
+	for try in $(seq 1 10); do
+	    output=$(s6-setuidgid abc ${backup_proj} db/mmonit.db ".backup /backup/${backup_filename}" 2>&1)
+	    test $? -eq 0 && break
+	    log "Backup failed (attempt ${try}): ${output}"
+	    sleep ${try}
+	done
 	;;
 esac
 
 # Verify backups
-test -e "/backup/${backup_filename}" || fail "ERROR: /backup/${backup_filename} not created"
-s6-setuidgid abc sqlite3 /backup/${backup_filename} .dump > ${tmpfile}
-test $? -ne 0 && fail "Backup verification failed"
-n_lines=$(cat ${tmpfile} | wc -l)
-test ${n_lines} -gt 3 || fail "Backup verification failed: only ${n_lines} lines!"
-rm -f ${tmpfile}
+test -s "/backup/${backup_filename}" || backup_fail "ERROR: /backup/${backup_filename} not created or empty"
+case "${database}" in
+    "mysql")
+	n_lines=$(wc -l /backup/${backup_filename})
+	n_lines="${n_lines%% *}"
+	test ${n_lines} -gt 3 || backup_fail "Backup verification failed: only ${n_lines} lines!"
+	;;
+    "postgresql")
+	fail "Backing up PostgresQL is not yet supported"
+	;;
+    "sqlite")  # Assume sqlist
+	s6-setuidgid abc ${backup_prog} /backup/${backup_filename} .dump > ${tmpfile}
+	test $? -ne 0 && backup_fail "Backup verification failed"
+	n_lines=$(wc -l ${tmpfile})
+	n_lines="${n_lines%% *}"
+	rm -f ${tmpfile}
+	test ${n_lines} -gt 3 || backup_fail "Backup verification failed: only ${n_lines} lines!"
+	;;
+esac
 log "/backup/${backup_filename} created and verified"
 
 # Clean up old backups
-output=$(s6-setuidgid abc find /backup -name \*_${type}.sq3 -ctime +${age} -delete -print 2>&1)
+output=$(s6-setuidgid abc find /backup -name \*_${type}.${suffix} -ctime +${age} -delete -print 2>&1)
 test $? -ne 0 && fail "Cleaning old backups with age ${age}: ${output}"
 test -n "${output}" && log "Cleaned older than ${age}: ${output//\n/ }"
 
