More generalized support for backups
Based on PR from @sseide.

1. Fix missing progname
2. Escape all use of shell variables
3. Store database config (esp credentials) in a config file
4. Do backup initialization in init-mmonit once at startup
5. Support database URLs with parameters and socket path to DB
6. Move back to sh from bash as we don't need bash features

diff --git a/root/etc/periodic/hourly/mmonit_backup b/root/etc/periodic/hourly/mmonit_backup
--- a/root/etc/periodic/hourly/mmonit_backup
+++ b/root/etc/periodic/hourly/mmonit_backup
@@ -1,4 +1,6 @@
-#!/usr/bin/with-contenv bash
+#!/usr/bin/with-contenv sh
+
+progname=$(basename "${0}")
 
 log () {
     echo "$(date +'%F %T') ${*}" | tee -a /config/logs/backup.log
@@ -10,14 +12,14 @@ fail () {
 }
 
 backup_fail () {
-    test -n "${backup_filename}" && rm -f ${backup_filename}
-    test -n "${tmpfile}" && rm -f ${tmpfile}
+    test -n "${backup_filename}" && rm -f "${backup_filename}"
+    test -n "${tmpfile}" && rm -f "${tmpfile}"
     log "${*}"
     exit 1
 }
 
 # If we stay in /root we'll get warnings when find finishes
-cd /config/mmonit-${MMONIT_VERSION} || fail "Unable to cd into /config/mmonit-${MMONIT_VERSION}"
+cd "/config/mmonit-${MMONIT_VERSION}" || fail "Unable to cd into /config/mmonit-${MMONIT_VERSION}"
 
 test -d /backup || fail "/backup is not a directory"
 test -w /backup || fail "/backup is not writable directory"
@@ -46,18 +48,12 @@ case ${0} in
 esac
 
 # Parse the database URL
-if [[ ${MMONIT_DATABASE_URL} =~ ^([^:]+)://([^:]+):([^@]+)@([^:]+):([0-9]+)/([a-zA-Z0-9]+)$ ]]; then
-    database="${BASH_REMATCH[1]}"
-    database_user="${BASH_REMATCH[2]}"
-    database_password="${BASH_REMATCH[3]}"
-    database_host="${BASH_REMATCH[4]}"
-    database_port="${BASH_REMATCH[5]}"
-    database_name="${BASH_REMATCH[6]}"
+database=$(expr "${MMONIT_DATABASE_URL}" : '\(.*\)://.*$')
+if [ -n "${database}" ]; then
     suffix=sql
     case "${database}" in
 	"mysql")
-	    backup_prog=mariadb-dump
-	    database_pkg=mariadb-client
+	    test -f /etc/mysqldump.cnf || fail "/etc/mysqldump.cnf not found"
 	    ;;
 	*)
 	    fail "Unsupported database type: ${database}"
@@ -66,27 +62,20 @@ if [[ ${MMONIT_DATABASE_URL} =~ ^([^:]+)://([^:]+):([^@]+)@([^:]+):([0-9]+)/([a-
 else
     database=sqlite3
     suffix=sq3
-    backup_prog=sqlite3
-    database_pkg=sqlite
 fi
 
-# Install the package we need
-which "${backup_prog}" >/dev/null || {
-    output=$(apk add -Uq "${database_pkg}" 2>&1)
-    test $? -ne 0 && fail "Unable to install ${database_pkg}: ${output}"
-}
-
 # Create backup filename and check that it exists
-backup_filename="mmonit_backup_$(date +'%FT%T')_${type}.${suffix}"
-test -e /backup/${backup_filename} && fail "/backup/${backup_filename} exists"
+backup_filename="/backup/mmonit_backup_$(date +'%FT%T')_${type}.${suffix}"
+test -e "${backup_filename}" && fail "${backup_filename} exists"
 tmpfile=$(mktemp -t ${progname}.XXXXXXXXXX)
 trap "rm -f ${backup_filename} ${tmpfile}" 1 2 3 13 15
 
 # Process backup per DB method
 case "${database}" in
     "mysql")
+	database_name="$(trurl --url "${MMONIT_DATABASE_URL}" --get '{path}' | cut -d '/' -f 2)"
 	for try in $(seq 1 10); do
-	    output=$(s6-setuidgid abc ${backup_prog} --no-defaults -h "${database_host}" -u "${database_user}" --password="${database_password}" --all-databases -r "/backup/${backup_filename}" 2>&1)
+	    output=$(s6-setuidgid abc mariadb-dump --defaults-file=/etc/mysqldump.cnf -r "${backup_filename}" "${database_name}" 2>&1)
 	    test $? -eq 0 && break
 	    log "Backup failed (attempt ${try}): ${output}"
 	    sleep ${try}
@@ -97,7 +86,7 @@ case "${database}" in
 	;;
     ""|"sqlite://")  # Assume sqlist
 	for try in $(seq 1 10); do
-	    output=$(s6-setuidgid abc ${backup_proj} db/mmonit.db ".backup /backup/${backup_filename}" 2>&1)
+	    output=$(s6-setuidgid abc sqlite3 db/mmonit.db ".backup ${backup_filename}" 2>&1)
 	    test $? -eq 0 && break
 	    log "Backup failed (attempt ${try}): ${output}"
 	    sleep ${try}
@@ -106,10 +95,10 @@ case "${database}" in
 esac
 
 # Verify backups
-test -s "/backup/${backup_filename}" || backup_fail "ERROR: /backup/${backup_filename} not created or empty"
+test -s "${backup_filename}" || backup_fail "ERROR: ${backup_filename} not created or empty"
 case "${database}" in
     "mysql")
-	n_lines=$(wc -l /backup/${backup_filename})
+	n_lines=$(wc -l ${backup_filename})
 	n_lines="${n_lines%% *}"
 	test ${n_lines} -gt 3 || backup_fail "Backup verification failed: only ${n_lines} lines!"
 	;;
@@ -117,15 +106,15 @@ case "${database}" in
 	fail "Backing up PostgresQL is not yet supported"
 	;;
     "sqlite")  # Assume sqlist
-	s6-setuidgid abc ${backup_prog} /backup/${backup_filename} .dump > ${tmpfile}
+	s6-setuidgid abc sqlite3 "${backup_filename}" .dump > "${tmpfile}"
 	test $? -ne 0 && backup_fail "Backup verification failed"
-	n_lines=$(wc -l ${tmpfile})
+	n_lines=$(wc -l "${tmpfile}")
 	n_lines="${n_lines%% *}"
-	rm -f ${tmpfile}
+	rm -f "${tmpfile}"
 	test ${n_lines} -gt 3 || backup_fail "Backup verification failed: only ${n_lines} lines!"
 	;;
 esac
-log "/backup/${backup_filename} created and verified"
+log "${backup_filename} created and verified"
 
 # Clean up old backups
 output=$(s6-setuidgid abc find /backup -name \*_${type}.* -mtime +${age} -delete -print 2>&1)
